### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by elvis82** [xinan2/lhdn-einvoice-malaysia-erpnext#1]
Hi when i install to erpnext getting error message like below

Installing myinvois...
Skipping fixture syncing from the file industrial_classification.json. Reason: Module import failed for Industrial Classification, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.industrial_classification'
Skipping fixture syncing from the file e_invoice_types.json. Reason: Module import failed for E-Invoice Types, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.e_invoice_types'
Skipping fixture syncing from the file item_classification_codes.json. Reason: Module import failed for Item Classification Codes, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.item_classification_codes'
Skipping fixture syncing from the file taxable_types.json. Reason: Module import failed for Taxable Types, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.taxable_types'
Skipping fixture syncing from the file state.json. Reason: Module import failed for State, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.core.doctype.state'
Updating Dashboard for myinvois

**Comment by mrehan675** [comment]
Send your issues in this email with more details (rehan.muhamad675@gmail.com).
